name: demo_2
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0-75.1.beta

dependencies:
  flame: ^1.30.1
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.4.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/spritesheet.png
  shaders:
    - shaders/sea.frag
    - shaders/ship_wake.frag
    - shaders/ship.frag
    - shaders/smoke.frag
    - shaders/vignette.frag
